[project]
name = "ten-apartment-be"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.3",
    "django-cors-headers>=4.9.0",
    "django-filter>=25.2",
    "django-phonenumber-field>=8.4.0",
    "djangorestframework>=3.17.0",
    "djangorestframework-simplejwt>=5.5.1",
    "djangorestframework-stubs>=3.16.8",
    "dotenv>=0.9.9",
    "markdown>=3.10.2",
    "phonenumbers>=9.0.26",
    "phonenumberslite>=9.0.26",
    "pillow>=12.1.1",
    "psycopg2>=2.9.11",
]
