# Generated by Django 6.0.3 on 2026-03-22 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartmenttype_price_apartment_booking_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartments.booking'),
            preserve_default=False,
        ),
    ]
