# Generated by Django 6.0.3 on 2026-03-22 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_booking_booking_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_day',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_days',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartments.schedule'),
            preserve_default=False,
        ),
    ]
