# Generated by Django 6.0.3 on 2026-03-23 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_days',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('date', 'apartment')},
        ),
        migrations.AddField(
            model_name='booking',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=25),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='label',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked'), ('maintenance', 'Maintenance')], default='available', max_length=25),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='apartments/'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='apartments/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='apartments.apartment'),
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.booking')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apartments.schedule')),
            ],
            options={
                'unique_together': {('booking', 'schedule')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='slots',
            field=models.ManyToManyField(through='apartments.BookingSlot', to='apartments.schedule'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_booking',
        ),
        migrations.AddField(
            model_name='schedule',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='apartments.price'),
            preserve_default=False,
        ),
    ]
