# Generated by Django 6.0.3 on 2026-03-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_alter_schedule_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartment',
            new_name='Apartments',
        ),
        migrations.RenameModel(
            old_name='ApartmentType',
            new_name='ApartmentTypes',
        ),
        migrations.RenameModel(
            old_name='BookingSlot',
            new_name='BookingSlots',
        ),
        migrations.RenameModel(
            old_name='Price',
            new_name='Prices',
        ),
    ]
