# Generated by Django 6.0.3 on 2026-03-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_rename_apartment_apartments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartments',
            new_name='Apartment',
        ),
        migrations.RenameModel(
            old_name='ApartmentTypes',
            new_name='ApartmentType',
        ),
        migrations.RenameModel(
            old_name='BookingSlots',
            new_name='BookingSlot',
        ),
        migrations.RenameModel(
            old_name='Prices',
            new_name='Price',
        ),
    ]
