# Generated by Django 6.0.3 on 2026-03-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_rename_apartments_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='video',
        ),
        migrations.CreateModel(
            name='ApartmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='apartments/photos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('apartments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apartments.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='apartments/videos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('apartments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='apartments.apartment')),
            ],
        ),
    ]
