# Generated by Django 6.0.3 on 2026-03-24 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_remove_apartment_photo_remove_apartment_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='apartments.price'),
        ),
    ]
