# Generated by Django 6.0.3 on 2026-03-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_alter_schedule_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartmentphoto',
            unique_together={('apartments', 'photo')},
        ),
        migrations.AlterUniqueTogether(
            name='apartmentvideo',
            unique_together={('apartments', 'video')},
        ),
        migrations.AddField(
            model_name='apartmentphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name='apartmentphoto',
            name='order',
        ),
        migrations.RemoveField(
            model_name='apartmentvideo',
            name='order',
        ),
    ]
