# Generated by Django 6.0.3 on 2026-04-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0012_remove_booking_apartments_remove_booking_slots_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='max_guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('name', 'type')},
        ),
    ]
