# Generated by Django 6.0.3 on 2026-04-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0013_alter_apartment_options_apartment_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='apartments', to='apartments.tag'),
        ),
    ]
