# Generated by Django 6.0.3 on 2026-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0014_tag_apartment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Area (m²)'),
        ),
    ]
