# Generated by Django 6.0.3 on 2026-04-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0015_add_area_to_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('contact', models.CharField(max_length=255, verbose_name='Phone or Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='apartments.apartment', verbose_name='Apartment')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ('-created_at',),
            },
        ),
    ]
